name: morpheme_extension
description: Superpowers for Dart. Collection of useful static extension methods.
version: 1.0.1
homepage: https://morpheme.design/
repository: https://github.com/morphemedesign/morpheme-flutter-library/tree/main/packages/morpheme_extension

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  time: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
