name: morpheme_inspector
description: A simple in-app for MorphemeHttp inspector. Intercepts and persists all HTTP requests and responses inside your application, and provides a UI for inspecting their content.
version: 2.0.1
homepage: https://morpheme.design/
repository: https://github.com/morphemedesign/morpheme-flutter-library/tree/main/packages/morpheme_inspector

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  sqflite: ^2.4.0
  sensors_plus: ^6.1.0
  flutter_local_notifications: ^18.0.0
  share_plus: ^10.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
